ALTER TABLE "public"."tb_admin Copy 1" DROP CONSTRAINT "fksjutrq4c3kk42tbqcsatk16mg" CASCADE;
ALTER TABLE "public"."tb_article" DROP CONSTRAINT "fk6cmdv1o1wu4fppbn884isd2xx" CASCADE;
ALTER TABLE "public"."tb_attraction" DROP CONSTRAINT "fkbgectjumbt6drg6j2cvyw7kln" CASCADE;
ALTER TABLE "public"."tb_notice" DROP CONSTRAINT "fk7mqu90kglmetv0ir3f2urplbw" CASCADE;
ALTER TABLE "public"."tb_notice" DROP CONSTRAINT "fkjjesbvmkt6o0med3r3scqb0hn" CASCADE;
ALTER TABLE "public"."tb_rating_score" DROP CONSTRAINT "fk43200cvnbo4qek1fcp54pqcw5" CASCADE;
ALTER TABLE "public"."tb_rating_score" DROP CONSTRAINT "fkovelwkitqhftd495smliaxnri" CASCADE;
ALTER TABLE "public"."tb_recommendation" DROP CONSTRAINT "fk1idxm262dlngntlpaqkyx6boe" CASCADE;
ALTER TABLE "public"."tb_recommendation" DROP CONSTRAINT "fknupgfedyunqhg2s8ro3gi7ttx" CASCADE;
ALTER TABLE "public"."tb_route" DROP CONSTRAINT "fkd1fscj1htu0bft6vng6daeg9t" CASCADE;
ALTER TABLE "public"."tb_staff" DROP CONSTRAINT "fkritnlo977ppjpp8bi7y1hrbn2" CASCADE;
ALTER TABLE "public"."tb_staff" DROP CONSTRAINT "fksqwtcf8x175s1txr0tw27x55a" CASCADE;
ALTER TABLE "public"."tb_tour_group" DROP CONSTRAINT "fkhxkjcb3h1vh7khi4g4quljg07" CASCADE;
ALTER TABLE "public"."tb_tour_group" DROP CONSTRAINT "fkqno0udmm21lv5lkpvvcyia9fj" CASCADE;
ALTER TABLE "public"."tb_user" DROP CONSTRAINT "fk221erl0f49i6qmbhbxmy9775x" CASCADE;
ALTER TABLE "public"."tb_user" DROP CONSTRAINT "fkdne9wxpjr872g76oxw2wmui2v" CASCADE;
ALTER TABLE "public"."tb_user_tags" DROP CONSTRAINT "fk2bkm8rkr29y52f5gu3a4qho7r" CASCADE;
ALTER TABLE "public"."tb_user_tags" DROP CONSTRAINT "fk3o4da15ioptqob08twd0odbjj" CASCADE;

ALTER TABLE "public"."tb_admin" DROP CONSTRAINT "uk_pbg5xkskbfb2mi7krqt9k8mly" CASCADE;
ALTER TABLE "public"."tb_admin Copy 1" DROP CONSTRAINT "uk_pbg5xkskbfb2mi7krqt9k8mly" CASCADE;
ALTER TABLE "public"."tb_user" DROP CONSTRAINT "uk_p55nmmsx9knp9yyp3mx5uqur2" CASCADE;

ALTER TABLE "public"."tb_admin" DROP CONSTRAINT "tb_admin_pkey" CASCADE;
ALTER TABLE "public"."tb_admin Copy 1" DROP CONSTRAINT "tb_admin_pkey" CASCADE;
ALTER TABLE "public"."tb_article" DROP CONSTRAINT "tb_article_pkey" CASCADE;
ALTER TABLE "public"."tb_attraction" DROP CONSTRAINT "tb_attraction_pkey" CASCADE;
ALTER TABLE "public"."tb_interest_tag" DROP CONSTRAINT "tb_interest_tag_pkey" CASCADE;
ALTER TABLE "public"."tb_notice" DROP CONSTRAINT "tb_notice_pkey" CASCADE;
ALTER TABLE "public"."tb_rating_score" DROP CONSTRAINT "tb_rating_score_pkey" CASCADE;
ALTER TABLE "public"."tb_recommendation" DROP CONSTRAINT "tb_recommendation_pkey" CASCADE;
ALTER TABLE "public"."tb_route" DROP CONSTRAINT "tb_route_pkey" CASCADE;
ALTER TABLE "public"."tb_showplace" DROP CONSTRAINT "tb_showplace_pkey" CASCADE;
ALTER TABLE "public"."tb_staff" DROP CONSTRAINT "tb_staff_pkey" CASCADE;
ALTER TABLE "public"."tb_tour_group" DROP CONSTRAINT "tb_tour_group_pkey" CASCADE;
ALTER TABLE "public"."tb_user" DROP CONSTRAINT "tb_user_pkey" CASCADE;
ALTER TABLE "public"."tb_user_tags" DROP CONSTRAINT "tb_user_tags_pkey" CASCADE;

DROP TABLE IF EXISTS "public"."tb_admin" CASCADE;
DROP TABLE IF EXISTS "public"."tb_admin Copy 1" CASCADE;
DROP TABLE IF EXISTS "public"."tb_article" CASCADE;
DROP TABLE IF EXISTS "public"."tb_attraction" CASCADE;
DROP TABLE IF EXISTS "public"."tb_interest_tag" CASCADE;
DROP TABLE IF EXISTS "public"."tb_notice" CASCADE;
DROP TABLE IF EXISTS "public"."tb_rating_score" CASCADE;
DROP TABLE IF EXISTS "public"."tb_recommendation" CASCADE;
DROP TABLE IF EXISTS "public"."tb_route" CASCADE;
DROP TABLE IF EXISTS "public"."tb_showplace" CASCADE;
DROP TABLE IF EXISTS "public"."tb_staff" CASCADE;
DROP TABLE IF EXISTS "public"."tb_tour_group" CASCADE;
DROP TABLE IF EXISTS "public"."tb_user" CASCADE;
DROP TABLE IF EXISTS "public"."tb_user_tags" CASCADE;

CREATE TABLE "public"."tb_admin" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "account" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "avatar" varchar(100) COLLATE "pg_catalog"."default",
  "introduction" varchar(255) COLLATE "pg_catalog"."default",
  "last_active_ip" inet,
  "name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'admin'::character varying,
  "password" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "roles" varchar(10) COLLATE "pg_catalog"."default" DEFAULT 'ADMIN'::character varying,
  "showplace_id" int8,
  CONSTRAINT "tb_admin_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_pbg5xkskbfb2mi7krqt9k8mly" UNIQUE ("account")
);
ALTER TABLE "public"."tb_admin" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_admin"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_admin"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_admin"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_admin"."account" IS '账号';
COMMENT ON COLUMN "public"."tb_admin"."avatar" IS '头像';
COMMENT ON COLUMN "public"."tb_admin"."introduction" IS '介绍';
COMMENT ON COLUMN "public"."tb_admin"."last_active_ip" IS '最后一次活跃IP';
COMMENT ON COLUMN "public"."tb_admin"."name" IS '姓名';
COMMENT ON COLUMN "public"."tb_admin"."password" IS '密码';
COMMENT ON COLUMN "public"."tb_admin"."roles" IS '角色权限';
COMMENT ON COLUMN "public"."tb_admin"."showplace_id" IS '所属景区';
COMMENT ON TABLE "public"."tb_admin" IS '景区管理员表';

CREATE TABLE "public"."tb_admin Copy 1" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "account" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "avatar" varchar(100) COLLATE "pg_catalog"."default",
  "introduction" varchar(255) COLLATE "pg_catalog"."default",
  "last_active_ip" inet,
  "name" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 'admin'::character varying,
  "password" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "roles" varchar(10) COLLATE "pg_catalog"."default" DEFAULT 'ADMIN'::character varying,
  "showplace_id" int8,
  CONSTRAINT "tb_admin_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_pbg5xkskbfb2mi7krqt9k8mly" UNIQUE ("account")
);
ALTER TABLE "public"."tb_admin Copy 1" OWNER TO "postgres";

CREATE TABLE "public"."tb_article" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "author" varchar(100) COLLATE "pg_catalog"."default" DEFAULT 'anonymous'::character varying,
  "content" text COLLATE "pg_catalog"."default",
  "cover_img" varchar(255) COLLATE "pg_catalog"."default",
  "title" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "showplace_id" int8,
  CONSTRAINT "tb_article_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_article" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_article"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_article"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_article"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_article"."author" IS '作者';
COMMENT ON COLUMN "public"."tb_article"."content" IS '内容';
COMMENT ON COLUMN "public"."tb_article"."cover_img" IS '头图';
COMMENT ON COLUMN "public"."tb_article"."title" IS '标题';
COMMENT ON COLUMN "public"."tb_article"."showplace_id" IS '关联景区';
COMMENT ON TABLE "public"."tb_article" IS '文章&攻略表';

CREATE TABLE "public"."tb_attraction" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "address" varchar(100) COLLATE "pg_catalog"."default",
  "amrt" int4 DEFAULT 0,
  "capacity" int4 DEFAULT 0,
  "category" varchar(20) COLLATE "pg_catalog"."default",
  "imgs_url" varchar(500) COLLATE "pg_catalog"."default",
  "infrastructure" jsonb,
  "introduction" text COLLATE "pg_catalog"."default",
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "open_note" varchar(255) COLLATE "pg_catalog"."default",
  "price" numeric(10,2) DEFAULT 0,
  "score" numeric(10,2) DEFAULT 5,
  "status" int2 DEFAULT 1,
  "tel" varchar(50) COLLATE "pg_catalog"."default",
  "parent_id" int8,
  CONSTRAINT "tb_attraction_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_attraction" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_attraction"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_attraction"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_attraction"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_attraction"."address" IS '地址';
COMMENT ON COLUMN "public"."tb_attraction"."amrt" IS '游客平均驻留时间';
COMMENT ON COLUMN "public"."tb_attraction"."capacity" IS '景点承载量';
COMMENT ON COLUMN "public"."tb_attraction"."category" IS '类别';
COMMENT ON COLUMN "public"."tb_attraction"."imgs_url" IS '图片 URL';
COMMENT ON COLUMN "public"."tb_attraction"."infrastructure" IS '基础设施';
COMMENT ON COLUMN "public"."tb_attraction"."introduction" IS '景点介绍';
COMMENT ON COLUMN "public"."tb_attraction"."latitude" IS '纬度';
COMMENT ON COLUMN "public"."tb_attraction"."longitude" IS '经度';
COMMENT ON COLUMN "public"."tb_attraction"."name" IS '景点名称';
COMMENT ON COLUMN "public"."tb_attraction"."open_note" IS '开放说明';
COMMENT ON COLUMN "public"."tb_attraction"."price" IS '价格';
COMMENT ON COLUMN "public"."tb_attraction"."score" IS '评分';
COMMENT ON COLUMN "public"."tb_attraction"."status" IS '状态 1开放0关闭2拥堵';
COMMENT ON COLUMN "public"."tb_attraction"."tel" IS '联系电话';
COMMENT ON COLUMN "public"."tb_attraction"."parent_id" IS '所属景点';
COMMENT ON TABLE "public"."tb_attraction" IS '景点信息表';

CREATE TABLE "public"."tb_interest_tag" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "tag_name" varchar(20) COLLATE "pg_catalog"."default",
  CONSTRAINT "tb_interest_tag_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_interest_tag" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_interest_tag"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_interest_tag"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_interest_tag"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_interest_tag"."tag_name" IS '标签名称';
COMMENT ON TABLE "public"."tb_interest_tag" IS '旅游兴趣标签表';

CREATE TABLE "public"."tb_notice" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "content" text COLLATE "pg_catalog"."default",
  "publish_time" timestamp(6),
  "publish_way" varchar(50) COLLATE "pg_catalog"."default" DEFAULT '手动推送'::character varying,
  "scope" int2 DEFAULT 0,
  "subject" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "type" varchar(20) COLLATE "pg_catalog"."default",
  "showplace_id" int8,
  "group_id" int8,
  CONSTRAINT "tb_notice_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_notice" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_notice"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_notice"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_notice"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_notice"."content" IS '内容';
COMMENT ON COLUMN "public"."tb_notice"."publish_time" IS '推送时间';
COMMENT ON COLUMN "public"."tb_notice"."publish_way" IS '推送方式';
COMMENT ON COLUMN "public"."tb_notice"."scope" IS '推送范围 0全局1群组';
COMMENT ON COLUMN "public"."tb_notice"."subject" IS '公告主题';
COMMENT ON COLUMN "public"."tb_notice"."type" IS '公告类型';
COMMENT ON COLUMN "public"."tb_notice"."showplace_id" IS '关联景区';
COMMENT ON COLUMN "public"."tb_notice"."group_id" IS '关联群组';
COMMENT ON TABLE "public"."tb_notice" IS '群组&景区公告表';

CREATE TABLE "public"."tb_rating_score" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "comment" varchar(500) COLLATE "pg_catalog"."default",
  "score" numeric(10,1) DEFAULT 5.0,
  "attraction_id" int8,
  "user_id" int8,
  CONSTRAINT "tb_rating_score_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_rating_score" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_rating_score"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_rating_score"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_rating_score"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_rating_score"."comment" IS '评论内容';
COMMENT ON COLUMN "public"."tb_rating_score"."score" IS '评分';
COMMENT ON COLUMN "public"."tb_rating_score"."attraction_id" IS '被评景点';
COMMENT ON COLUMN "public"."tb_rating_score"."user_id" IS '评分用户';
COMMENT ON TABLE "public"."tb_rating_score" IS '游客评分表';

CREATE TABLE "public"."tb_recommendation" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6) NOT NULL,
  "gmt_modified" timestamp(6),
  "propensity" numeric(10,2),
  "status" int2 DEFAULT 0,
  "attraction_id" int8,
  "user_id" int8,
  CONSTRAINT "tb_recommendation_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_recommendation" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_recommendation"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_recommendation"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_recommendation"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_recommendation"."propensity" IS '倾向系数';
COMMENT ON COLUMN "public"."tb_recommendation"."status" IS '0未去过1去过';
COMMENT ON COLUMN "public"."tb_recommendation"."attraction_id" IS '景点 ID';
COMMENT ON COLUMN "public"."tb_recommendation"."user_id" IS '用户 ID';
COMMENT ON TABLE "public"."tb_recommendation" IS '用户推荐表';

CREATE TABLE "public"."tb_route" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "hot" numeric(10,1) DEFAULT 5.0,
  "introduction" text COLLATE "pg_catalog"."default",
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "note" varchar(255) COLLATE "pg_catalog"."default",
  "showplace_id" int8,
  "road_list" jsonb,
  "cover_img" varchar(255) COLLATE "pg_catalog"."default",
  CONSTRAINT "tb_route_pkey" PRIMARY KEY ("gmt_create")
);
ALTER TABLE "public"."tb_route" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_route"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_route"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_route"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_route"."hot" IS '热度';
COMMENT ON COLUMN "public"."tb_route"."introduction" IS '路线介绍';
COMMENT ON COLUMN "public"."tb_route"."name" IS '路线名称';
COMMENT ON COLUMN "public"."tb_route"."note" IS '路线说明';
COMMENT ON COLUMN "public"."tb_route"."showplace_id" IS '所属景区';
COMMENT ON COLUMN "public"."tb_route"."road_list" IS '途经点';
COMMENT ON COLUMN "public"."tb_route"."cover_img" IS '头图';
COMMENT ON TABLE "public"."tb_route" IS '热门路线表';

CREATE TABLE "public"."tb_showplace" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "address" varchar(100) COLLATE "pg_catalog"."default",
  "capacity" int4 DEFAULT 0,
  "category" varchar(50) COLLATE "pg_catalog"."default",
  "imgs_url" varchar(255) COLLATE "pg_catalog"."default",
  "introduction" text COLLATE "pg_catalog"."default",
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "open_note" varchar(255) COLLATE "pg_catalog"."default",
  "score" numeric(10,2) DEFAULT 5,
  "status" int2 DEFAULT 1,
  "tels" varchar(100) COLLATE "pg_catalog"."default",
  CONSTRAINT "tb_showplace_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_showplace" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_showplace"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_showplace"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_showplace"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_showplace"."address" IS '地址';
COMMENT ON COLUMN "public"."tb_showplace"."capacity" IS '承载量';
COMMENT ON COLUMN "public"."tb_showplace"."category" IS '标签';
COMMENT ON COLUMN "public"."tb_showplace"."imgs_url" IS '图片 URL';
COMMENT ON COLUMN "public"."tb_showplace"."introduction" IS '景区介绍';
COMMENT ON COLUMN "public"."tb_showplace"."latitude" IS '纬度';
COMMENT ON COLUMN "public"."tb_showplace"."longitude" IS '经度';
COMMENT ON COLUMN "public"."tb_showplace"."name" IS '名称';
COMMENT ON COLUMN "public"."tb_showplace"."open_note" IS '开放说明';
COMMENT ON COLUMN "public"."tb_showplace"."score" IS '评分';
COMMENT ON COLUMN "public"."tb_showplace"."status" IS '状态';
COMMENT ON COLUMN "public"."tb_showplace"."tels" IS '联系电话';
COMMENT ON TABLE "public"."tb_showplace" IS '景区信息表';

CREATE TABLE "public"."tb_staff" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "address" varchar(100) COLLATE "pg_catalog"."default",
  "entry_time" date,
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "responsibility" varchar(100) COLLATE "pg_catalog"."default",
  "status" int2 NOT NULL DEFAULT 1,
  "tel" varchar(50) COLLATE "pg_catalog"."default",
  "attraction_id" int8,
  "showplace_id" int8,
  CONSTRAINT "tb_staff_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_staff" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_staff"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_staff"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_staff"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_staff"."address" IS '地址';
COMMENT ON COLUMN "public"."tb_staff"."entry_time" IS '入职时间';
COMMENT ON COLUMN "public"."tb_staff"."latitude" IS '纬度';
COMMENT ON COLUMN "public"."tb_staff"."longitude" IS '经度';
COMMENT ON COLUMN "public"."tb_staff"."name" IS '名字';
COMMENT ON COLUMN "public"."tb_staff"."responsibility" IS '职责';
COMMENT ON COLUMN "public"."tb_staff"."status" IS '状态 1在岗0离开';
COMMENT ON COLUMN "public"."tb_staff"."tel" IS '联系电话';
COMMENT ON COLUMN "public"."tb_staff"."attraction_id" IS '管辖景点';
COMMENT ON COLUMN "public"."tb_staff"."showplace_id" IS '所属景区';
COMMENT ON TABLE "public"."tb_staff" IS '景区员工表';

CREATE TABLE "public"."tb_tour_group" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "group_info" text COLLATE "pg_catalog"."default",
  "group_limit_size" int4 DEFAULT 100,
  "group_name" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "group_size" int4 DEFAULT 0,
  "invite_code" varchar(20) COLLATE "pg_catalog"."default",
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "status" int2 DEFAULT 1,
  "creator_id" int8,
  "showplace_id" int8,
  CONSTRAINT "tb_tour_group_pkey" PRIMARY KEY ("id")
);
ALTER TABLE "public"."tb_tour_group" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_tour_group"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_tour_group"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_tour_group"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_tour_group"."group_info" IS '群组介绍';
COMMENT ON COLUMN "public"."tb_tour_group"."group_limit_size" IS '最大成员限制';
COMMENT ON COLUMN "public"."tb_tour_group"."group_name" IS '群组名称';
COMMENT ON COLUMN "public"."tb_tour_group"."group_size" IS '群组当前成员';
COMMENT ON COLUMN "public"."tb_tour_group"."invite_code" IS '邀请码';
COMMENT ON COLUMN "public"."tb_tour_group"."latitude" IS '维度';
COMMENT ON COLUMN "public"."tb_tour_group"."longitude" IS '经度';
COMMENT ON COLUMN "public"."tb_tour_group"."status" IS '状态';
COMMENT ON COLUMN "public"."tb_tour_group"."creator_id" IS '创建者';
COMMENT ON COLUMN "public"."tb_tour_group"."showplace_id" IS '所属景区';
COMMENT ON TABLE "public"."tb_tour_group" IS '群组信息表';

CREATE TABLE "public"."tb_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "gmt_create" timestamp(6),
  "gmt_modified" timestamp(6),
  "address" varchar(100) COLLATE "pg_catalog"."default",
  "avatar" varchar(255) COLLATE "pg_catalog"."default",
  "birthday" date,
  "gender" varchar(10) COLLATE "pg_catalog"."default",
  "latitude" numeric(10,6),
  "longitude" numeric(10,6),
  "openid" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "phone" varchar(50) COLLATE "pg_catalog"."default",
  "status" int2 DEFAULT 0,
  "showplace_id" int8,
  "group_id" int8,
  "name" varchar(50) COLLATE "pg_catalog"."default",
  CONSTRAINT "tb_user_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "uk_p55nmmsx9knp9yyp3mx5uqur2" UNIQUE ("openid")
);
ALTER TABLE "public"."tb_user" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_user"."id" IS '主键';
COMMENT ON COLUMN "public"."tb_user"."gmt_create" IS '创建时间';
COMMENT ON COLUMN "public"."tb_user"."gmt_modified" IS '最后一次修改时间';
COMMENT ON COLUMN "public"."tb_user"."address" IS '地址';
COMMENT ON COLUMN "public"."tb_user"."avatar" IS '头像';
COMMENT ON COLUMN "public"."tb_user"."birthday" IS '生日';
COMMENT ON COLUMN "public"."tb_user"."gender" IS '性别';
COMMENT ON COLUMN "public"."tb_user"."latitude" IS '纬度';
COMMENT ON COLUMN "public"."tb_user"."longitude" IS '经度';
COMMENT ON COLUMN "public"."tb_user"."openid" IS '微信openid';
COMMENT ON COLUMN "public"."tb_user"."phone" IS '手机号码';
COMMENT ON COLUMN "public"."tb_user"."status" IS '状态 1在线0离线';
COMMENT ON COLUMN "public"."tb_user"."showplace_id" IS '所在景区';
COMMENT ON COLUMN "public"."tb_user"."group_id" IS '所属群组';
COMMENT ON COLUMN "public"."tb_user"."name" IS '姓名';
COMMENT ON TABLE "public"."tb_user" IS '小程序用户信息表';

CREATE TABLE "public"."tb_user_tags" (
  "user_id" int8 NOT NULL,
  "tag_id" int8 NOT NULL,
  CONSTRAINT "tb_user_tags_pkey" PRIMARY KEY ("user_id", "tag_id")
);
ALTER TABLE "public"."tb_user_tags" OWNER TO "postgres";
COMMENT ON COLUMN "public"."tb_user_tags"."user_id" IS '用户 ID';
COMMENT ON COLUMN "public"."tb_user_tags"."tag_id" IS '兴趣标签 ID';
COMMENT ON TABLE "public"."tb_user_tags" IS '用户兴趣关联表';

ALTER TABLE "public"."tb_admin Copy 1" ADD CONSTRAINT "fksjutrq4c3kk42tbqcsatk16mg" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_article" ADD CONSTRAINT "fk6cmdv1o1wu4fppbn884isd2xx" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_attraction" ADD CONSTRAINT "fkbgectjumbt6drg6j2cvyw7kln" FOREIGN KEY ("parent_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_notice" ADD CONSTRAINT "fk7mqu90kglmetv0ir3f2urplbw" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_notice" ADD CONSTRAINT "fkjjesbvmkt6o0med3r3scqb0hn" FOREIGN KEY ("group_id") REFERENCES "public"."tb_tour_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_rating_score" ADD CONSTRAINT "fk43200cvnbo4qek1fcp54pqcw5" FOREIGN KEY ("attraction_id") REFERENCES "public"."tb_attraction" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_rating_score" ADD CONSTRAINT "fkovelwkitqhftd495smliaxnri" FOREIGN KEY ("user_id") REFERENCES "public"."tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_recommendation" ADD CONSTRAINT "fk1idxm262dlngntlpaqkyx6boe" FOREIGN KEY ("attraction_id") REFERENCES "public"."tb_attraction" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_recommendation" ADD CONSTRAINT "fknupgfedyunqhg2s8ro3gi7ttx" FOREIGN KEY ("user_id") REFERENCES "public"."tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_route" ADD CONSTRAINT "fkd1fscj1htu0bft6vng6daeg9t" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_staff" ADD CONSTRAINT "fkritnlo977ppjpp8bi7y1hrbn2" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_staff" ADD CONSTRAINT "fksqwtcf8x175s1txr0tw27x55a" FOREIGN KEY ("attraction_id") REFERENCES "public"."tb_attraction" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_tour_group" ADD CONSTRAINT "fkhxkjcb3h1vh7khi4g4quljg07" FOREIGN KEY ("creator_id") REFERENCES "public"."tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_tour_group" ADD CONSTRAINT "fkqno0udmm21lv5lkpvvcyia9fj" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_user" ADD CONSTRAINT "fk221erl0f49i6qmbhbxmy9775x" FOREIGN KEY ("showplace_id") REFERENCES "public"."tb_showplace" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_user" ADD CONSTRAINT "fkdne9wxpjr872g76oxw2wmui2v" FOREIGN KEY ("group_id") REFERENCES "public"."tb_tour_group" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_user_tags" ADD CONSTRAINT "fk2bkm8rkr29y52f5gu3a4qho7r" FOREIGN KEY ("user_id") REFERENCES "public"."tb_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."tb_user_tags" ADD CONSTRAINT "fk3o4da15ioptqob08twd0odbjj" FOREIGN KEY ("tag_id") REFERENCES "public"."tb_interest_tag" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

